[PARAMETERS]
INTERVAL_LENGTH = 100
OPERATING_DAY_LIST = [ "091", "092", "093", "094", "095", "096", "097", "098", "099", "100", "101", "102", "103", "104", "105",]
DETECTOR_LIST = [ "143-5", "143-6", "143-7",]

[STATUS]
N = 0
N_GLITCH = 0
N_LONG = 0
N_NO_GLITCH = 0
